### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'replace')

### ISSUE THREAD

**Issue by straimtheone** [samgozman/finvizor#164]
Since 2023-04-19 the library stop working with the following error:
Error: TypeError: Cannot read properties of undefined (reading 'replace')
    at C:\Users\angel\Development\mpro-notify\stocks\node_modules\finvizor\lib\quote.js:126:27
    at step (C:\Users\angel\Development\mpro-notify\stocks\node_modules\finvizor\lib\quote.js:33:23)
    at Object.next (C:\Users\angel\Development\mpro-notify\stocks\node_modules\finvizor\lib\quote.js:14:53)
    at fulfilled (C:\Users\angel\Development\mpro-notify\stocks\node_modules\finvizor\lib\quote.js:5:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

finvizor library version 1.1.2

**Comment by samgozman** [comment]
Thanks for the issue! Will fix this soon

**Comment by samgozman** [comment]
Fixed in [1.1.3](https://github.com/samgozman/finvizor/releases/tag/1.1.3)
